// flow-typed signature: 69e483cc508c882c1939940bc6a91bb9
// flow-typed version: <<STUB>>/cors-anywhere_v^0.4.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cors-anywhere'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cors-anywhere' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cors-anywhere/lib/cors-anywhere' {
  declare module.exports: any;
}

declare module 'cors-anywhere/lib/rate-limit' {
  declare module.exports: any;
}

declare module 'cors-anywhere/lib/regexp-top-level-domain' {
  declare module.exports: any;
}

declare module 'cors-anywhere/server' {
  declare module.exports: any;
}

declare module 'cors-anywhere/test/child' {
  declare module.exports: any;
}

declare module 'cors-anywhere/test/setup' {
  declare module.exports: any;
}

declare module 'cors-anywhere/test/test-examples' {
  declare module.exports: any;
}

declare module 'cors-anywhere/test/test-memory' {
  declare module.exports: any;
}

declare module 'cors-anywhere/test/test-ratelimit' {
  declare module.exports: any;
}

declare module 'cors-anywhere/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cors-anywhere/lib/cors-anywhere.js' {
  declare module.exports: $Exports<'cors-anywhere/lib/cors-anywhere'>;
}
declare module 'cors-anywhere/lib/rate-limit.js' {
  declare module.exports: $Exports<'cors-anywhere/lib/rate-limit'>;
}
declare module 'cors-anywhere/lib/regexp-top-level-domain.js' {
  declare module.exports: $Exports<'cors-anywhere/lib/regexp-top-level-domain'>;
}
declare module 'cors-anywhere/server.js' {
  declare module.exports: $Exports<'cors-anywhere/server'>;
}
declare module 'cors-anywhere/test/child.js' {
  declare module.exports: $Exports<'cors-anywhere/test/child'>;
}
declare module 'cors-anywhere/test/setup.js' {
  declare module.exports: $Exports<'cors-anywhere/test/setup'>;
}
declare module 'cors-anywhere/test/test-examples.js' {
  declare module.exports: $Exports<'cors-anywhere/test/test-examples'>;
}
declare module 'cors-anywhere/test/test-memory.js' {
  declare module.exports: $Exports<'cors-anywhere/test/test-memory'>;
}
declare module 'cors-anywhere/test/test-ratelimit.js' {
  declare module.exports: $Exports<'cors-anywhere/test/test-ratelimit'>;
}
declare module 'cors-anywhere/test/test.js' {
  declare module.exports: $Exports<'cors-anywhere/test/test'>;
}
