// flow-typed signature: 967ea3ad44fbd9aa323275e303924f1c
// flow-typed version: <<STUB>>/postcss-sorting_v^4.0.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-sorting'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-sorting' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-sorting/lib/calcAtRulePatternPriority' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/calcRulePatternPriority' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/checkOption' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/createExpectedOrder' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/createExpectedPropertiesOrder' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/getComments' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/getContainingNode' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/getOrderData' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/getPropertiesOrderData' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/isAtVariable' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/isCustomProperty' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/isDollarVariable' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/isRuleWithNodes' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/isStandardSyntaxProperty' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/order/index' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/processLastComments' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/processMostNodes' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/properties-order/index' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/sorting' {
  declare module.exports: any;
}

declare module 'postcss-sorting/lib/validateOptions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-sorting/index' {
  declare module.exports: $Exports<'postcss-sorting'>;
}
declare module 'postcss-sorting/index.js' {
  declare module.exports: $Exports<'postcss-sorting'>;
}
declare module 'postcss-sorting/lib/calcAtRulePatternPriority.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/calcAtRulePatternPriority'>;
}
declare module 'postcss-sorting/lib/calcRulePatternPriority.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/calcRulePatternPriority'>;
}
declare module 'postcss-sorting/lib/checkOption.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/checkOption'>;
}
declare module 'postcss-sorting/lib/createExpectedOrder.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/createExpectedOrder'>;
}
declare module 'postcss-sorting/lib/createExpectedPropertiesOrder.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/createExpectedPropertiesOrder'>;
}
declare module 'postcss-sorting/lib/getComments.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/getComments'>;
}
declare module 'postcss-sorting/lib/getContainingNode.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/getContainingNode'>;
}
declare module 'postcss-sorting/lib/getOrderData.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/getOrderData'>;
}
declare module 'postcss-sorting/lib/getPropertiesOrderData.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/getPropertiesOrderData'>;
}
declare module 'postcss-sorting/lib/isAtVariable.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/isAtVariable'>;
}
declare module 'postcss-sorting/lib/isCustomProperty.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/isCustomProperty'>;
}
declare module 'postcss-sorting/lib/isDollarVariable.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/isDollarVariable'>;
}
declare module 'postcss-sorting/lib/isRuleWithNodes.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/isRuleWithNodes'>;
}
declare module 'postcss-sorting/lib/isStandardSyntaxProperty.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/isStandardSyntaxProperty'>;
}
declare module 'postcss-sorting/lib/order/index.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/order/index'>;
}
declare module 'postcss-sorting/lib/processLastComments.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/processLastComments'>;
}
declare module 'postcss-sorting/lib/processMostNodes.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/processMostNodes'>;
}
declare module 'postcss-sorting/lib/properties-order/index.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/properties-order/index'>;
}
declare module 'postcss-sorting/lib/sorting.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/sorting'>;
}
declare module 'postcss-sorting/lib/validateOptions.js' {
  declare module.exports: $Exports<'postcss-sorting/lib/validateOptions'>;
}
