// flow-typed signature: 195551575c7805a1e87b3c537a582ca1
// flow-typed version: <<STUB>>/prettier-webpack-plugin_v^1.2.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-webpack-plugin/__tests__/index' {
  declare module.exports: any;
}

declare module 'prettier-webpack-plugin/__tests__/sample-code' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-webpack-plugin/__tests__/index.js' {
  declare module.exports: $Exports<'prettier-webpack-plugin/__tests__/index'>;
}
declare module 'prettier-webpack-plugin/__tests__/sample-code.js' {
  declare module.exports: $Exports<'prettier-webpack-plugin/__tests__/sample-code'>;
}
declare module 'prettier-webpack-plugin/index' {
  declare module.exports: $Exports<'prettier-webpack-plugin'>;
}
declare module 'prettier-webpack-plugin/index.js' {
  declare module.exports: $Exports<'prettier-webpack-plugin'>;
}
