// flow-typed signature: 8ad9620116e1d6d1775845937108b2cd
// flow-typed version: <<STUB>>/react-loading-skeleton_v^1.1.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loading-skeleton'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loading-skeleton' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loading-skeleton/dist/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loading-skeleton/dist/bundle.js' {
  declare module.exports: $Exports<'react-loading-skeleton/dist/bundle'>;
}
