// flow-typed signature: c8a8ab0ceb91cfa0ec1ce0d9068db45e
// flow-typed version: <<STUB>>/rss-parser_v^3.7.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rss-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rss-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rss-parser/browser' {
  declare module.exports: any;
}

declare module 'rss-parser/dist/rss-parser' {
  declare module.exports: any;
}

declare module 'rss-parser/dist/rss-parser.min' {
  declare module.exports: any;
}

declare module 'rss-parser/lib/fields' {
  declare module.exports: any;
}

declare module 'rss-parser/lib/parser' {
  declare module.exports: any;
}

declare module 'rss-parser/lib/utils' {
  declare module.exports: any;
}

declare module 'rss-parser/test/browser' {
  declare module.exports: any;
}

declare module 'rss-parser/test/parser' {
  declare module.exports: any;
}

declare module 'rss-parser/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rss-parser/browser.js' {
  declare module.exports: $Exports<'rss-parser/browser'>;
}
declare module 'rss-parser/dist/rss-parser.js' {
  declare module.exports: $Exports<'rss-parser/dist/rss-parser'>;
}
declare module 'rss-parser/dist/rss-parser.min.js' {
  declare module.exports: $Exports<'rss-parser/dist/rss-parser.min'>;
}
declare module 'rss-parser/index' {
  declare module.exports: $Exports<'rss-parser'>;
}
declare module 'rss-parser/index.js' {
  declare module.exports: $Exports<'rss-parser'>;
}
declare module 'rss-parser/lib/fields.js' {
  declare module.exports: $Exports<'rss-parser/lib/fields'>;
}
declare module 'rss-parser/lib/parser.js' {
  declare module.exports: $Exports<'rss-parser/lib/parser'>;
}
declare module 'rss-parser/lib/utils.js' {
  declare module.exports: $Exports<'rss-parser/lib/utils'>;
}
declare module 'rss-parser/test/browser.js' {
  declare module.exports: $Exports<'rss-parser/test/browser'>;
}
declare module 'rss-parser/test/parser.js' {
  declare module.exports: $Exports<'rss-parser/test/parser'>;
}
declare module 'rss-parser/webpack.config.js' {
  declare module.exports: $Exports<'rss-parser/webpack.config'>;
}
