// flow-typed signature: 4030757ad8d5cd4c3703e265eb889543
// flow-typed version: <<STUB>>/@tiddo/flow-json-config_v^1.0.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tiddo/flow-json-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tiddo/flow-json-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@tiddo/flow-json-config/index' {
  declare module.exports: $Exports<'@tiddo/flow-json-config'>;
}
declare module '@tiddo/flow-json-config/index.js' {
  declare module.exports: $Exports<'@tiddo/flow-json-config'>;
}
