// flow-typed signature: 8fa7952606d7aa61affbc87a6a64777c
// flow-typed version: <<STUB>>/@types/classnames_v^2.2.7/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/classnames'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/classnames' {
  declare module.exports: any;
}
