// flow-typed signature: a607cbc6f3e24f55d04fb67a7ce8f192
// flow-typed version: <<STUB>>/@types/react-dom_v^16.0.9/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-dom' {
  declare module.exports: any;
}
