// flow-typed signature: be565ca4c7c3251364e15f21359a8477
// flow-typed version: <<STUB>>/@types/react_v^16.7.6/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
