// flow-typed signature: cec210459db96e17f9cbdd5885f63f92
// flow-typed version: <<STUB>>/@material-ui/core/Card_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/Card'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/Card' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/Card/Card' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/Card/Card.js' {
  declare module.exports: $Exports<'@material-ui/core/Card/Card'>;
}
declare module '@material-ui/core/Card/index' {
  declare module.exports: $Exports<'@material-ui/core/Card'>;
}
declare module '@material-ui/core/Card/index.js' {
  declare module.exports: $Exports<'@material-ui/core/Card'>;
}
