// flow-typed signature: 0e9c1f4b82eb488ae4f6fdf32d1d1249
// flow-typed version: <<STUB>>/@material-ui/core/CardActionArea_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/CardActionArea'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/CardActionArea' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/CardActionArea/CardActionArea' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/CardActionArea/CardActionArea.js' {
  declare module.exports: $Exports<'@material-ui/core/CardActionArea/CardActionArea'>;
}
declare module '@material-ui/core/CardActionArea/index' {
  declare module.exports: $Exports<'@material-ui/core/CardActionArea'>;
}
declare module '@material-ui/core/CardActionArea/index.js' {
  declare module.exports: $Exports<'@material-ui/core/CardActionArea'>;
}
