// flow-typed signature: 651b3fdf6ac599245b6bb5278692f457
// flow-typed version: <<STUB>>/@material-ui/core/CardContent_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/CardContent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/CardContent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/CardContent/CardContent' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/CardContent/CardContent.js' {
  declare module.exports: $Exports<'@material-ui/core/CardContent/CardContent'>;
}
declare module '@material-ui/core/CardContent/index' {
  declare module.exports: $Exports<'@material-ui/core/CardContent'>;
}
declare module '@material-ui/core/CardContent/index.js' {
  declare module.exports: $Exports<'@material-ui/core/CardContent'>;
}
