// flow-typed signature: 53b5628442161be3d510f3dc778c3337
// flow-typed version: <<STUB>>/@material-ui/core/Chip_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/Chip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/Chip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/Chip/Chip' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/Chip/Chip.js' {
  declare module.exports: $Exports<'@material-ui/core/Chip/Chip'>;
}
declare module '@material-ui/core/Chip/index' {
  declare module.exports: $Exports<'@material-ui/core/Chip'>;
}
declare module '@material-ui/core/Chip/index.js' {
  declare module.exports: $Exports<'@material-ui/core/Chip'>;
}
