// flow-typed signature: 7a46cc3dbfcc7433da9787e30adf41ac
// flow-typed version: <<STUB>>/@material-ui/core/Divider_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/Divider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/Divider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/Divider/Divider' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/Divider/Divider.js' {
  declare module.exports: $Exports<'@material-ui/core/Divider/Divider'>;
}
declare module '@material-ui/core/Divider/index' {
  declare module.exports: $Exports<'@material-ui/core/Divider'>;
}
declare module '@material-ui/core/Divider/index.js' {
  declare module.exports: $Exports<'@material-ui/core/Divider'>;
}
