// flow-typed signature: c71571f3caabe4429c9fe5ec5639a595
// flow-typed version: <<STUB>>/@material-ui/core/ExpansionPanelSummary_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/ExpansionPanelSummary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/ExpansionPanelSummary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/ExpansionPanelSummary/ExpansionPanelSummary' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/ExpansionPanelSummary/ExpansionPanelSummary.js' {
  declare module.exports: $Exports<'@material-ui/core/ExpansionPanelSummary/ExpansionPanelSummary'>;
}
declare module '@material-ui/core/ExpansionPanelSummary/index' {
  declare module.exports: $Exports<'@material-ui/core/ExpansionPanelSummary'>;
}
declare module '@material-ui/core/ExpansionPanelSummary/index.js' {
  declare module.exports: $Exports<'@material-ui/core/ExpansionPanelSummary'>;
}
