// flow-typed signature: 3af3223bd603afe4651e04546d80b430
// flow-typed version: <<STUB>>/@material-ui/core/ExpansionPanelActions_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/ExpansionPanelActions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/ExpansionPanelActions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/ExpansionPanelActions/ExpansionPanelActions' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/ExpansionPanelActions/ExpansionPanelActions.js' {
  declare module.exports: $Exports<'@material-ui/core/ExpansionPanelActions/ExpansionPanelActions'>;
}
declare module '@material-ui/core/ExpansionPanelActions/index' {
  declare module.exports: $Exports<'@material-ui/core/ExpansionPanelActions'>;
}
declare module '@material-ui/core/ExpansionPanelActions/index.js' {
  declare module.exports: $Exports<'@material-ui/core/ExpansionPanelActions'>;
}
