// flow-typed signature: a1495241012157f7373763f67019a7a8
// flow-typed version: <<STUB>>/@material-ui/core/ExpansionPanelDetails_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/ExpansionPanelDetails'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/ExpansionPanelDetails' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/ExpansionPanelDetails/ExpansionPanelDetails' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/ExpansionPanelDetails/ExpansionPanelDetails.js' {
  declare module.exports: $Exports<'@material-ui/core/ExpansionPanelDetails/ExpansionPanelDetails'>;
}
declare module '@material-ui/core/ExpansionPanelDetails/index' {
  declare module.exports: $Exports<'@material-ui/core/ExpansionPanelDetails'>;
}
declare module '@material-ui/core/ExpansionPanelDetails/index.js' {
  declare module.exports: $Exports<'@material-ui/core/ExpansionPanelDetails'>;
}
