// flow-typed signature: 9885c046a3a6d6c653086d631f92c259
// flow-typed version: <<STUB>>/@material-ui/core/ExpansionPanel_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/ExpansionPanel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/ExpansionPanel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/ExpansionPanel/ExpansionPanel' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/ExpansionPanel/ExpansionPanel.js' {
  declare module.exports: $Exports<'@material-ui/core/ExpansionPanel/ExpansionPanel'>;
}
declare module '@material-ui/core/ExpansionPanel/index' {
  declare module.exports: $Exports<'@material-ui/core/ExpansionPanel'>;
}
declare module '@material-ui/core/ExpansionPanel/index.js' {
  declare module.exports: $Exports<'@material-ui/core/ExpansionPanel'>;
}
