// flow-typed signature: b1545aff2fcee754783b290a8a53105f
// flow-typed version: <<STUB>>/@material-ui/core/Fab_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/Fab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/Fab' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/Fab/Fab' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/Fab/Fab.js' {
  declare module.exports: $Exports<'@material-ui/core/Fab/Fab'>;
}
declare module '@material-ui/core/Fab/index' {
  declare module.exports: $Exports<'@material-ui/core/Fab'>;
}
declare module '@material-ui/core/Fab/index.js' {
  declare module.exports: $Exports<'@material-ui/core/Fab'>;
}
