// flow-typed signature: 4a7a689923344a45ae076c4abe5d2c5d
// flow-typed version: <<STUB>>/@material-ui/core/Grid_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/Grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/Grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/Grid/Grid' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/Grid/Grid.js' {
  declare module.exports: $Exports<'@material-ui/core/Grid/Grid'>;
}
declare module '@material-ui/core/Grid/index' {
  declare module.exports: $Exports<'@material-ui/core/Grid'>;
}
declare module '@material-ui/core/Grid/index.js' {
  declare module.exports: $Exports<'@material-ui/core/Grid'>;
}
