// flow-typed signature: 66fa6bde62ff2111c54939f8493eef51
// flow-typed version: <<STUB>>/@material-ui/core/TableCell_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/TableCell'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/TableCell' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/TableCell/TableCell' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/TableCell/index' {
  declare module.exports: $Exports<'@material-ui/core/TableCell'>;
}
declare module '@material-ui/core/TableCell/index.js' {
  declare module.exports: $Exports<'@material-ui/core/TableCell'>;
}
declare module '@material-ui/core/TableCell/TableCell.js' {
  declare module.exports: $Exports<'@material-ui/core/TableCell/TableCell'>;
}
