// flow-typed signature: 9149fc160b789ff518d25377371a0110
// flow-typed version: <<STUB>>/@material-ui/core/TableHead_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/TableHead'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/TableHead' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/TableHead/TableHead' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/TableHead/index' {
  declare module.exports: $Exports<'@material-ui/core/TableHead'>;
}
declare module '@material-ui/core/TableHead/index.js' {
  declare module.exports: $Exports<'@material-ui/core/TableHead'>;
}
declare module '@material-ui/core/TableHead/TableHead.js' {
  declare module.exports: $Exports<'@material-ui/core/TableHead/TableHead'>;
}
