// flow-typed signature: ed24ee33730958d5684136309fd0f627
// flow-typed version: <<STUB>>/@material-ui/core/TableRow_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/TableRow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/TableRow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/TableRow/TableRow' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/TableRow/index' {
  declare module.exports: $Exports<'@material-ui/core/TableRow'>;
}
declare module '@material-ui/core/TableRow/index.js' {
  declare module.exports: $Exports<'@material-ui/core/TableRow'>;
}
declare module '@material-ui/core/TableRow/TableRow.js' {
  declare module.exports: $Exports<'@material-ui/core/TableRow/TableRow'>;
}
