// flow-typed signature: 3077bbb4a972f3136b4bf5e76494337f
// flow-typed version: <<STUB>>/@material-ui/core/Table_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/Table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/Table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/Table/Table' {
  declare module.exports: any;
}

declare module '@material-ui/core/Table/TableContext' {
  declare module.exports: any;
}

declare module '@material-ui/core/Table/Tablelvl2Context' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/Table/index' {
  declare module.exports: $Exports<'@material-ui/core/Table'>;
}
declare module '@material-ui/core/Table/index.js' {
  declare module.exports: $Exports<'@material-ui/core/Table'>;
}
declare module '@material-ui/core/Table/Table.js' {
  declare module.exports: $Exports<'@material-ui/core/Table/Table'>;
}
declare module '@material-ui/core/Table/TableContext.js' {
  declare module.exports: $Exports<'@material-ui/core/Table/TableContext'>;
}
declare module '@material-ui/core/Table/Tablelvl2Context.js' {
  declare module.exports: $Exports<'@material-ui/core/Table/Tablelvl2Context'>;
}
