// flow-typed signature: 9729e08a71c7e1bf9d0cc42453d98f9f
// flow-typed version: <<STUB>>/@material-ui/core/Typography_v1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/Typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/Typography' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/Typography/Typography' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/Typography/index' {
  declare module.exports: $Exports<'@material-ui/core/Typography'>;
}
declare module '@material-ui/core/Typography/index.js' {
  declare module.exports: $Exports<'@material-ui/core/Typography'>;
}
declare module '@material-ui/core/Typography/Typography.js' {
  declare module.exports: $Exports<'@material-ui/core/Typography/Typography'>;
}
